### PR TITLE
[Request] Build release?

### PR DESCRIPTION
**Pull request by Bluscream**
Can you build it and add it as release?

### CODE REVIEW

**Comment by Mahekaru** [comment]
Sorry I'm not on here like everyday so I I'm a little late getting this merged.

**Comment by Bluscream** [comment]
This was not meant as a pull request, but you have issues disabled

**Comment by Mahekaru** [comment]
Oops. Ok I get what you're saying now. Yea, I'll look at it tonight and get an exe out so it's usable. Or at least so you don't actually have to run it through console. Thanks for the heads up Bluescream.

**Comment by Mahekaru** [comment]
so I looked last night on how to make this into an exe and wasn't very successful. Looks like He's using electron to do it, but when I tried it, it didn't work :(. I'll keep at it, but I'll have to figure it out as I go.

**Comment by Bluscream** [comment]
Okay :/

**Comment by Mahekaru** [comment]
If it means anything you can download the code and if you have node.js installed just do npm install then npm start and it will boot up.
er... if you don't have node.js installed do that first.

**Pull request merged**
